#version 430
#extension GL_ARB_separate_shader_objects : enable

layout(binding = 0, rgba8) uniform image2D input_image;
layout(binding = 2, rgba8) uniform image2D output_image;

void main() {
  uint x = gl_GlobalInvocationID.x;
  uint y = gl_GlobalInvocationID.y;
  ivec2 coord = ivec2(x, y);

  vec4 col = imageLoad(input_image, coord);
  // TODO: lambert? some kind of shading. Need normals and colors passed properly.

  imageStore(output_image, coord, col);
}
