#version 430
#extension GL_ARB_separate_shader_objects : enable

struct mat5 {
  mat4 main;
  vec4 column;
  vec4 row;
  float ww;
};

layout(set = 0, binding = 0) uniform CameraBufferObject {
  mat5 view;
  mat5 proj;
} camera;

layout(set = 1, binding = 0) uniform Dimensions {
  int width;
  int height;
} dim;

layout(set = 2, binding = 0) buffer InputVertices {
  vec4 pos;
} inputVertices;

layout(set = 2, binding = 1) buffer OutputVertices {
  vec4 pos;
} outputVertices;

void main() {
}
